ci:
    autofix_prs: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: spotless
        name: spotless
        entry: bash -c 'mvn spotless:apply'
        language: system
        files: \.(java|xml|json|md)$
