# This rule is not used by the project podmortem itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over podmortem.redhat.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podmortem
    app.kubernetes.io/managed-by: kustomize
  name: podmortemconfig-admin-role
rules:
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs
  verbs:
  - '*'
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs/status
  verbs:
  - get
