# This rule is not used by the project podmortem itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to podmortem.redhat.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podmortem
    app.kubernetes.io/managed-by: kustomize
  name: podmortemconfig-viewer-role
rules:
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs/status
  verbs:
  - get
