---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - podmortem.redhat.com
  resources:
  - podmortemconfigs/status
  verbs:
  - get
  - patch
  - update
