---
apiVersion: v1
kind: Service
metadata:
  name: podmortem-ai-interface-service
  namespace: podmortem-system
spec:
  selector:
    app: podmortem-ai-interface-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
