---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aiproviders.podmortem.redhat.com
spec:
  group: podmortem.redhat.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              providerId:
                type: string
                description: "Unique identifier for the AI provider (e.g., 'openai', 'ollama')"
              apiUrl:
                type: string
                description: "Base URL for the AI provider API"
              modelId:
                type: string
                description: "Model identifier to use for inference"
              authenticationRef:
                type: object
                properties:
                  secretName:
                    type: string
                  secretKey:
                    type: string
                description: "Reference to Kubernetes Secret containing authentication credentials"
              timeoutSeconds:
                type: integer
                default: 30
                description: "Request timeout in seconds"
              maxRetries:
                type: integer
                default: 3
                description: "Maximum number of retry attempts"
              cachingEnabled:
                type: boolean
                default: true
                description: "Enable response caching for similar requests"
              promptTemplate:
                type: string
                description: "Custom prompt template to use"
              maxTokens:
                type: integer
                default: 500
                description: "Maximum number of tokens to generate"
              temperature:
                type: number
                default: 0.3
                description: "Temperature for AI generation"
              additionalConfig:
                type: object
                additionalProperties:
                  type: string
                description: "Provider-specific additional configuration"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Ready", "Failed"]
              message:
                type: string
              lastValidated:
                type: string
                format: date-time
              observedGeneration:
                type: integer
                format: int64
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: aiproviders
    singular: aiprovider
    kind: AIProvider
    shortNames:
    - aip
