---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-log-parser-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmortem-log-parser-service
  template:
    metadata:
      labels:
        app: podmortem-log-parser-service
    spec:
      containers:
      - name: log-parser
        image: ghcr.io/podmortem/podmortem-log-parser:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: podmortem-log-parser-service
spec:
  selector:
    app: podmortem-log-parser-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP