---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-log-parser-service
  namespace: podmortem-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmortem-log-parser-service
  template:
    metadata:
      labels:
        app: podmortem-log-parser-service
    spec:
      # Ensure this pod runs on the same node as the operator for ReadWriteOnce volume sharing
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: podmortem-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - name: log-parser
        image: ghcr.io/podmortem/podmortem-log-parser:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pattern-cache
          mountPath: /shared/patterns
          readOnly: true
      volumes:
      - name: pattern-cache
        persistentVolumeClaim:
          claimName: pattern-cache-pvc
