---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podmortem-log-parser-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podmortem-log-parser-service
  template:
    metadata:
      labels:
        app: podmortem-log-parser-service
    spec:
      containers:
      - name: log-parser
        image: ghcr.io/podmortem/podmortem-log-parser:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pattern-cache
          mountPath: /shared/patterns
          readOnly: true
      volumes:
      - name: pattern-cache
        persistentVolumeClaim:
          claimName: pattern-cache-pvc
