---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podmortem-operator
  namespace: podmortem-system
  labels:
    app: podmortem-operator
    component: operator
automountServiceAccountToken: true
