apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmortem-operator
rules:
  - apiGroups: ["podmortem.redhat.com"]
    resources: ["aiproviders", "podmortems", "patternlibraries"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets", "events"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "patch"]
  - apiGroups: ["podmortem.redhat.com"]
    resources: ["*"]
    verbs: ["patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podmortem-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podmortem-operator
subjects:
  - kind: ServiceAccount
    name: podmortem-operator
    namespace: podmortem-system
