---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: patternlibraries.podmortem.redhat.com
spec:
  group: podmortem.redhat.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              repositories:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name identifier for the repository"
                    url:
                      type: string
                      description: "Git repository URL containing pattern libraries"
                    branch:
                      type: string
                      default: "main"
                      description: "Git branch to use"
                    credentials:
                      type: object
                      properties:
                        secretRef:
                          type: string
                          description: "Name of Kubernetes secret containing Git credentials"
                      description: "Authentication credentials for private repositories"
                  required: ["name", "url"]
              refreshInterval:
                type: string
                default: "1h"
                description: "How often to sync patterns from repositories (e.g., '30m', '1h')"
              enabledLibraries:
                type: array
                items:
                  type: string
                description: "List of pattern library IDs to enable from the repositories"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Syncing", "Ready", "Failed"]
                description: "Current state of the pattern library"
              message:
                type: string
                description: "Human-readable status message"
              lastSyncTime:
                type: string
                format: date-time
                description: "When patterns were last synchronized"
              syncedRepositories:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    lastCommit:
                      type: string
                    syncTime:
                      type: string
                      format: date-time
                    status:
                      type: string
                      enum: ["Success", "Failed"]
                    error:
                      type: string
                description: "Status of each configured repository"
              availableLibraries:
                type: array
                items:
                  type: string
                description: "List of discovered pattern libraries from all repositories"
              observedGeneration:
                type: integer
                format: int64
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: patternlibraries
    singular: patternlibrary
    kind: PatternLibrary
    shortNames:
    - pl
