---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pattern-cache-pvc
  namespace: podmortem-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
