---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmortems.podmortem.redhat.com
spec:
  group: podmortem.redhat.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              podSelector:
                type: object
                properties:
                  matchLabels:
                    type: object
                    additionalProperties:
                      type: string
                  matchExpressions:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          type: array
                          items:
                            type: string
                description: "Label selector for pods to monitor"
              aiProviderRef:
                type: object
                properties:
                  name:
                    type: string
                    description: "Name of the AIProvider resource to use for analysis"
                  namespace:
                    type: string
                    description: "Namespace of the AIProvider resource (optional, defaults to same namespace)"
                description: "Reference to an AI provider for generating explanations"
              aiAnalysisEnabled:
                type: boolean
                default: true
                description: "Enable AI-powered analysis for this pod failure"
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Ready", "Processing", "Error"]
              message:
                type: string
              lastUpdate:
                type: string
                format: date-time
              observedGeneration:
                type: integer
                format: int64
              recentFailures:
                type: array
                items:
                  type: object
                  properties:
                    podName:
                      type: string
                    podNamespace:
                      type: string
                    failureTime:
                      type: string
                      format: date-time
                    analysisStatus:
                      type: string
                    explanation:
                      type: string
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: podmortems
    singular: podmortem
    kind: Podmortem
    shortNames:
    - pm
