apiVersion: podmortem.redhat.com/v1alpha1
kind: PodmortemConfig
metadata:
  labels:
    app.kubernetes.io/name: podmortem
    app.kubernetes.io/managed-by: kustomize
  name: podmortemconfig-sample
spec:
  # TODO(user): Add fields here
