name: Cleanup Container Images

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

env:
  IMAGE_NAME: podmortem-operator

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          owner: podmortem
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: false
          # Keep only: release tags (v1.2.3), latest-dev, latest, and deps-cache
          ignore-versions: '^(v\d+\.\d+\.\d+.*|latest-dev|latest|deps-cache)$'
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Delete untagged images
        uses: actions/delete-package-versions@v5
        with:
          owner: podmortem
          package-name: ${{ env.IMAGE_NAME }}
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
